name: QuantBull.info
tagline: Keep informed about the adventurous development of the QuantBull Project!
markdown: redcarpet
pygments: true

permalink: /:year/:month/:title/
owner:
    name: Carlos Soares
    twitter: cmpsoares
    github: cmpsoares91
    disqus_shortname: quantbullinfo
    
ga_id: UA-50856212-1
ga_username: quantbull.info
        
timezone: Portugal
       
