name: QuantBull.info | Keep informed about the adventures in the development of the QuantBull Project
markdown: redcarpet
pygments: true

permalink: /:year/:month/:title/
owner:
    name: Carlos Soares
    twitter: cmpsoares91
    github: cmpsoares
    disqus_shortname: quantbullinfo
    
ga_id: UA-50856212-1
ga_username: cmpsoares91@gmail.com
        
timezone: #
       
